### ISSUE TITLE
collection installation fails 

### ISSUE THREAD

**Issue by eprasad** [ansible-collections/splunk.es#16] opened 2020-12-22 07:42 UTC
##### SUMMARY

Trying to install the splunk.se collection reading the doc provided but it fails with following error all the time

root@splunk:~# ansible-galaxy collection install splunk.es

- downloading role 'collection', owned by
 [WARNING]: - collection was NOT installed successfully: Content has no field named 'owner'

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
root@splunk:~#
---- with ignore-errors
root@splunk:~# ansible-galaxy collection install splunk.es --ignore-errors
- downloading role 'collection', owned by
 [WARNING]: - collection was NOT installed successfully: Content has no field named 'owner'

- downloading role 'es', owned by splunk
 [WARNING]: - splunk.es was NOT installed successfully: - sorry, splunk.es was not found on
https://galaxy.ansible.com.

root@splunk:~#
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION
```
root@splunk:~# ansible --version
ansible 2.5.1

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
Ubuntu 18.4

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by Akasurde** [comment] 2020-12-23 04:52
@eprasad Thanks for reporting this issue. Could you please upgrade Ansible version to latest?

Since, I am not able to reproduce this issue - 

```
# ansible-galaxy collection install splunk.es
Process install dependency map
Starting collection install process
Installing 'splunk.es:1.0.2' to '/Volumes/data/src/collections/ansible_collections/splunk/es'
Downloading https://galaxy.ansible.com/download/splunk-es-1.0.2.tar.gz to /Users/akasurde/.ansible/tmp/ansible-local-55627d3amspbo/tmpqnz2o8ld
splunk.es (1.0.2) was installed successfully
```

**Comment by justjais** [comment] 2021-02-12 07:23
Not able to reproduce the issue, so closing the issue

**Closed as completed by justjais** 2021-02-12 07:23 UTC
